codecov:
  notify:
    require_ci_to_pass: yes
comment:
  layout: "header, changes, diff, sunburst"

coverage:
  ignore:
  - Carthage/.*
  - Carthage/.*
  - .*Tests.swift
  - .*Spec.swift
  - .Stub*.swift
  - .*Mock.swift
  - RemakeStoreTests/*
  - SCServiceKitTests/*
  - SCLayoutKitTests/*
  
  status:
    patch: false